allow-expect-in-tests          = true
allow-panic-in-tests           = true
allow-unwrap-in-tests          = true
cognitive-complexity-threshold = 25
max-include-file-size          = 1000000
stack-size-threshold           = 512000
too-many-arguments-threshold   = 7
too-many-lines-threshold       = 100
type-complexity-threshold      = 250
