[package]
description            = "Linux container-side tools for decune"
edition.workspace      = true
license.workspace      = true
name                   = "decune-container-tools"
publish.workspace      = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[dependencies]
anyhow                    = "1.0.102"
decune-container-protocol = {path = "../decune-container-protocol"}
serde_json                = "1.0.150"
tokio                     = {features = ["io-util", "net", "rt-multi-thread"], version = "1.52.3"}
